apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: exsys-staging
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    selector:
        matchLabels:
            app: frontend-deployment
    template:
        metadata:
            labels:
                app: frontend-deployment
        spec:
            automountServiceAccountToken: false
            containers:
                - name: frontend-deployment
                  resources:
                      limits:
                          cpu: "0.05"
                          memory: "500Mi"
                      requests:
                          cpu: "0.01"
                          memory: "25Mi"
                  image: "rhaversen/exsys-frontend:4d8f9ac6aa5915e676bbd0c1495e99d5140586bf"
                  imagePullPolicy: Always
                  livenessProbe:
                      httpGet:
                          path: service/livez
                          port: 5000
                      periodSeconds: 10
                      initialDelaySeconds: 15
                      failureThreshold: 5
                  readinessProbe:
                      httpGet:
                          path: service/readyz
                          port: 5000
                      periodSeconds: 10
                      initialDelaySeconds: 15
                      failureThreshold: 5
                  ports:
                      - containerPort: 5000
                  envFrom:
                      - secretRef:
                            name: frontend-secrets
