apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: exsys-staging
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    selector:
        matchLabels:
            app: frontend-deployment
    template:
        metadata:
            labels:
                app: frontend-deployment
        spec:
            automountServiceAccountToken: false
            containers:
                - name: frontend-deployment
                  resources:
                      limits:
                          cpu: "0.2"
                          memory: "256Mi"
                      requests:
                          cpu: "0.1"
                          memory: "125Mi"
                  image: "rhaversen/exsys-frontend:40d9986a59e9afc6b95b5f1aed590412a4612a58"
                  imagePullPolicy: Always
                  livenessProbe:
                      httpGet:
                          path: service/livez
                          port: 5000
                      periodSeconds: 10
                      initialDelaySeconds: 15
                      failureThreshold: 5
                  readinessProbe:
                      httpGet:
                          path: service/readyz
                          port: 5000
                      periodSeconds: 10
                      initialDelaySeconds: 15
                      failureThreshold: 5
                  ports:
                      - containerPort: 5000
                  envFrom:
                      - secretRef:
                            name: frontend-secrets
